steps:
  # Clean and checkout
  - checkout: self
    clean: all
    continueOnError: 'false'

  - task: DownloadPipelineArtifact@1
    inputs:
      targetPath: $(System.ArtifactsDirectory)

  # Build, test and generate artifact output
  - powershell: .\build.ps1 -target Stage-Deploy -Verbose
    displayName: 'Build, test and generate artifact output on working directory'
    continueOnError: 'false'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      GITTER_ROOM_ID: $(GITTER_ROOM_ID)
      GITTER_TOKEN: $(GITTER_TOKEN)
      NUGET_API_KEY: $(NUGET_API_KEY)
      NUGET_API_URL: $(NUGET_API_URL)
